---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:1.41.0
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: pull ubuntu test image
          command: 'docker pull ubuntu:bionic-20200112'
      - run:
          name: pull alpine test image
          command: 'docker pull alpine:3.11.3'
      - run:
          name: test extract
          command: 'cargo test'
